kind: pipeline
name: default

steps:
- name: docker  
  image: plugins/docker
  settings:
    repo: finstreet/test-deployment
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    tags: latest-drone-${DRONE_SOURCE_BRANCH}

- name: ssh commands
  image: appleboy/drone-ssh
  settings:
    host: 
      from_secret: ssh_host
    username: root
    key:
      from_secret: ssh_key
    script:
      - cd /var/Wordpress/ && ./restart.sh
