kind: pipeline
name: default

steps:
- name: build
  image: docker:latest
  volumes:
    - name: docker_sock
      path: /var/run/docker.sock
  commands:
    - docker build -t $DRONE_REPO.latest-drone .
