kind: pipeline
name: default

steps:
- name: docker  
  image: plugins/docker
  settings:
    repo: finstreet/test-deployment
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    tags: latest-drone-$DRONE_BRANCH
